services:
  database:
    image: "postgres:16.2-alpine3.19"
    container_name: postgres
    restart: always
    env_file:
      - ../../.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
  app:
    build: ../../
    container_name: loginApi
    ports:
      - 3000:3000
    env_file:
      - ../../.env
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
